In [49]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
import pandas as pd

In [50]:
from tensorflow import keras
model = keras.models.load_model('/content/drive/MyDrive/Colab Notebooks/fake news/resources/fake_news2.h5')

In [51]:
testset= pd.read_csv('/content/drive/MyDrive/Colab Notebooks/fake news/resources/val.csv')

In [52]:
x_val= testset.iloc[:,:-1].values
y_val= testset.iloc[:,-1].values
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y1_val=le.fit_transform(y_val)

In [53]:
import nltk
nltk.download('wordnet')
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


In [54]:
import re 
 #stop words the,a etc
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer #stemming simplifies words eg loved->love minimising dimension of the sparse matrix
corpus = []
for i in range(0, len(testset)):  # NTS last me change kar lena range
  review= re.sub('[^a-zA-Z]', ' ', testset['text'][i])    # ^ == NOT
  review= review.lower()
  review= review.split()
  #ps=PorterStemmer()
  all_stopwords=stopwords.words('english')
  all_stopwords.remove('not') # NTS stopword aur customize as per req
  review=[lemmatizer.lemmatize(word) for word in review if not word in set(all_stopwords)] #apply steming to all words except stopwords
  review = ' '.join(review)
  corpus.append(review)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [55]:
from tensorflow.keras.preprocessing.text import one_hot
voc_size=5000
res=[one_hot(words,voc_size)for words in corpus] 

In [56]:
import tensorflow as tf

In [57]:
x= testset.iloc[:,:-1].values
temp=0
max=0
for i in x:
  temp=0
  j=str(i)
  for words in j.split(' '):
    temp+=1

  if temp>max:
    max=temp
print(max)

97


In [58]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
sent=98
embedded=pad_sequences(res,padding='pre',maxlen=sent)
print(embedded)

[[   0    0    0 ... 1407 4487 3761]
 [   0    0    0 ... 1798 1964 2915]
 [   0    0    0 ... 2876 4984 1204]
 ...
 [   0    0    0 ... 3752 3359  930]
 [   0    0    0 ... 1964 4210 1832]
 [   0    0    0 ... 3101  892 4917]]


In [64]:
# y_pred=model.predict(embedded)

y_pred=model.predict_classes( embedded, batch_size=32, verbose=1)

AttributeError: ignored

In [60]:

# for i in range(0,len(y_pred)):
#   if(y_pred[i]>=0.50):
#     y_pred[i]=1
#   else:
#     y_pred[i]=0

In [61]:
# y_pr_text=[]
# for i in range(0,len(y_pred)):
#   if(y_pred[i]==1.0):
#     y_pr_text.append('real')
#   else:
#     y_pr_text.append('fake')

In [62]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y1_val, y_pred)
print(cm)
accuracy_score(y1_val, y_pred)

[[  114 11094]
 [  300 27158]]


0.7053225055604407

In [63]:
# import numpy as np
# import pandas as pd
# prediction = pd.DataFrame(y_pr_text, columns=['label']).to_csv('/content/drive/MyDrive/Colab Notebooks/fake news/resources/prediction2.csv')